### ISSUE TITLE
Overlapping text in chat log

### ISSUE THREAD

**Issue by burntorangejedi** [TheMouseNest/Chattynator#44]
### What version(s) of WoW are you using?

Retail

### What version of Chattynator?

106

### What isn't working? What was supposed to happen?

Looks like after a /refresh, I get overlapping text in the chat log.

<img width="540" height="273" alt="Image" src="https://github.com/user-attachments/assets/2c77cf48-cf77-499c-a4d1-717eeece0213" />

### Are you experiencing any lua errors

No LUA errors

### Anything else?

Nope - other that that, it's been perfect!

**Comment by plusmouse** [comment]
Are you using the default font, or a custom one?

**Comment by lordblackadder** [comment]
I've been seeing the same since the first release I installed so it's not a recent issue. The font is explicitly set and it's a very rare occurrence

<img width="648" height="73" alt="Image" src="https://github.com/user-attachments/assets/e934509d-6ba1-41b2-bc3c-73a6b5da6852" />

**Comment by Avranim** [comment]
I can confirm that I also experience this issue relatively infrequently. I've only seen it happen when a line spills over to the next that was made at the same second, /reload will correct via message history. My own font used is Expressway with outline.

**Comment by plusmouse** [comment]
This should be fixed now

**Comment by Avranim** [comment]
This appears to still happen. Attaching a screenshot where it happened today, latest version and there was a fair gap between the message and the following one (which was a system message of someone else joining a raid). Presumably this is where the addon expects the line to have ended and not spilled over?

Text = Expressway with outline, set in Chattynator.

<img width="343" height="35" alt="Image" src="https://github.com/user-attachments/assets/6903fd9e-2f86-40dc-a318-0b6b8f98c97c" />

**Comment by plusmouse** [comment]
Going to assume this is fixed now :)

**Comment by Malivil** [comment]
<img width="489" height="79" alt="Image" src="https://github.com/user-attachments/assets/c87a3855-0f0a-44f3-baef-12f797edd202" />

This is still happening for me on Chattynator v123
